### ISSUE TITLE
ZLK38050 firmware issue

### ISSUE THREAD

**Issue by cygnusnow** [MicrosemiVoiceProcessing/ZLK38AVS#3]
Hi,

So far as I know, ZLK38050 can upload the firmware and config file. For this project, we don't have any firmware and config file. 

Does it mean that there is no need to upload the firmware?  I found we have SPI/I2C code and HBI driver.

Can you please tell me how to get the right firmware and config file?

**Comment by bonyjean1** [comment]
Hi,
The SDK includes SPI  and  I2C drivers that can be used to access the ZL380xx device or load one of the supported firmware/config images into the device. 

You can download that full SDK (ZLS38100), and desired firmware load from our Software Donwload Site (sds.microsemi.com) if you already have an account, or work with your supplier, he/she can work the details with you on how to get access to the site.

Best regards,
Jean

**Comment by bonyjean1** [comment]
Hi,
Who is your supplier? What company are you working for?

Best regards,
Jean

**Comment by cygnusnow** [comment]
Thanks for your quick reply.  I am working for UBTEDU. I am not sure about the suppliers.  Maybe it is arrow.

**Comment by cygnusnow** [comment]
We are going to use ZLK38050 on our new robot. It seems I got a wrong firmware.  I run the demo application and re-configure the ZLK38050, it works. But when I using VERSION 2.2.0 firmware, there is no sound output to DAC. 
That's why I raised this issue here.  👍   Thanks.

**Comment by bonyjean1** [comment]
Hi,
The I2S port on the ZL38050 device can be configured as master or  slave. The firmware loaded into the device by the kit has the ZL380xx device I2S port configured accordingly . The firmware 2.2 you downloaded has the I2S default configuration as I2S slave, which why you are not hearing audio.

The ALSA machine driver code included within the kit has the .dat_fmt configured expecting the ZL380xx device to be the I2S master providing both the I2S Bit and LR clocks to the Raspberry pi.  Therefore, if you load a different firmware into the ZL380xx device you must explicitly configure the I2S of the ZL380xx to timing master. 

You have 2 possible solutions:
1)
 I'm not sure how you are controlling the ZL38050 device now, if you have our demo apps to read/write registers of the device you can simply:
(Write 0x81F2 into register 0x262, then  write 0x0002 into register 0x0006)

Or, if you are using our MiTuner tool, simply go to the Audio Path Configuration and click the "Timing Master" check box of the TDMA and click "Apply"

2)
Alternatively, if you prefer the Raspberry pi to be I2S master, then you need to modify the 
ZLK38AVS/vproc_sdk/platform/raspberry/driver/sound/lnxalsa/soc/machine/microsemi-dac.c

From : 
static struct snd_soc_dai_link snd_microsemi_dac_dai[] = {
    {
    .name           = "Microsemi DAC",
    .stream_name    = "Microsemi DAC ",
    .cpu_dai_name   = "bcm2708-i2s.0",
    .codec_dai_name = "zl380xx-dai",
    .platform_name  = "bcm2708-i2s.0",
    .codec_name     = "zl380-codec",
    .dai_fmt        = SND_SOC_DAIFMT_I2S | SND_SOC_DAIFMT_NB_NF |
                        SND_SOC_DAIFMT_CBM_CFM,
    .ops            = &snd_microsemi_dac_ops,
    .init           = snd_microsemi_dac_init,
    },
};

TO:
static struct snd_soc_dai_link snd_microsemi_dac_dai[] = {
    {
    .name           = "Microsemi DAC",
    .stream_name    = "Microsemi DAC ",
    .cpu_dai_name   = "bcm2708-i2s.0",
    .codec_dai_name = "zl380xx-dai",
    .platform_name  = "bcm2708-i2s.0",
    .codec_name     = "zl380-codec",
    .dai_fmt        = SND_SOC_DAIFMT_I2S | SND_SOC_DAIFMT_NB_NF |
                        SND_SOC_DAIFMT_CBS_CFS,
    .ops            = &snd_microsemi_dac_ops,
    .init           = snd_microsemi_dac_init,
    },
};

Best regards,
Jean

**Comment by cygnusnow** [comment]
@bonyjean1   It works.  Thank you very much.

**Comment by bhura112** [comment]
can anyone please tell me about the .s3 Firmware image format for zl380xx audio processors, because I am writing zl38051 drivers based on pic32 microcontrollers. and I want to load .s3 files using microcontroller i2c and I don't what is the meaning of all data. 

S0080307E306031027CA
S3250008020000001C0F00100F000001000000000000000D0000000E000000000000000000006A
S325000802200000000000010005000200000000000000000000000000000000000000000000A8
S32500080240000000000000000000000000000000000000000000000000000000000000000090
S32500080260800401F2C0C000000100010100040006000000000000000000000000000000006C
S32500080280000000020004000600000000000000000000000000000000000000000000000044
S325000802A0C000000000040000000000000000000000070000000C0000815EFFF181E0FFF139
S325000802C003ECFFF6000000000000000000000000000000000000000000000000000000002C
S325000802E00000000000000000000000000000000000000000000000000000000000000000F0
S3250008030020008880044C0000000000400810A0000078019AF8CE00330200030005AFFFFF9C
S32500080320A55012000028001F3040010C00060A3F04A1003F0020000048010096000A0004A4
S32500080340000010000000000500000000000000000000000011223344139409C40005000057
S3250008036000130E800A00400000261A00080004000FA006400B0B00000A05001000AA20083C
S3250008038004000200780102800023003C280108A1000000017FDF00203628010000C8001166
S325000803A07E0078006000000201F400967F007C007000CF170DEB0638012F0018000000314C
S325000803C000007D710064266616C30001FFC40014001C040C000C133F287A669D000082408F
S325000803E0100B502D2020000201F000780050000401F000780050087A010001900004171759
S3250008040007140320003300000B2713580C5215600DA217A20F0E1A21123D170A00000000BD
S3250008042000000000000000000190019000000000000000000000000000007FFF0001000A03
S3250008044000010000000000000000000000000000000000000000000000000000000000008D
